### ISSUE TITLE
Research how to add BE to Firefox add-ons

### ISSUE THREAD

**Issue by Jolg42** [opt-out-tools/opt-out#20]
**Objective**
Research how to get browser extension into add-ons

**Description**
Browser extensions need to be signed to install into the release or beta versions of Firefox. It requires some research to make sure we are doing it properly

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Read [add-on distribution agreement](https://extensionworkshop.com/documentation/publish/firefox-add-on-distribution-agreement/)
- [ ] Read the [review policy](https://extensionworkshop.com/documentation/publish/add-on-policies/) 
- [ ] Read about how to get our browser extension [featured](https://extensionworkshop.com/documentation/publish/recommended-extensions/)

**Comment by malteserteresa** [comment]
Brilliant thank you!

**Comment by ribicn-softerrific** [comment]
https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/

**Comment by ribicn-softerrific** [comment]
When extensions is registered application ID is written in 
"manifest.json -> applications -> gecko -> id -> <ID>"

**Comment by river-honer** [comment]
WE DID IT FOR THE MARCH 8 RELEASE YES!
