### ISSUE TITLE
Puppeteer with Jest for testing DOM

### ISSUE THREAD

**Issue by river-honer** [opt-out-tools/opt-out#82]
**Objective**
Implement puppeteer and write a few tests using it, to test the streamed message handler in opt-out-ext.js

**Description**
Puppeteer is a library for mocking the DOM in Jest. It would be useful for creating an environment to test the interface between the page and the browser. When it comes to testing this application (like many other applications) it's best to test the interfaces instead of internal functions. Integration tests are worth more than unit tests, however unit tests are important too. I would like to add Puppeteer to the test environment and write up some tests so that testing the effects of the code on DOM nodes can be controlled and doesn't require ONLY debugging in the browser.

**Skills**
Javascript, Testing Methodology

**Tools**
Jest, Puppeteer

**Time Estimation**
6 hr

**Tasks**

- [ ] Add Puppeteer to the test framework
- [ ] Create first test with Puppeteer, probably on the stream `opt-out-ext.js`
- [ ] Create some more tests possibly within the scope of this task, maybe as other task

**Comment by river-honer** [comment]
Ok I was confused about Puppeteer, since it's actually for controlling headless chrome. I need another library to test this. But the principle still stands, having some tests of the streaming and messaging. Ignore for now, will do more research
