### ISSUE TITLE
Implement Webpack

### ISSUE THREAD

**Issue by river-honer** [opt-out-tools/opt-out#86]
**Objective**
Implement webpack. This will support future development to help add future build tools such as: babel es6+, typescript, css preprocessors, react/vue, etc.

**Description**
Move all working files to `src` folder, which are built by webpack to `dist` folder, where entire web extension will be run out of. 

**Skills**
Webpack, node, javascript.

**Tools**
Webpack, terminal, text editor

**Time Estimation**
5 hr

**Tasks**

- [x] Move all files to src
- [x] Get webpack to build the same file structure
- [x] Set up development build process
