### ISSUE TITLE
Document release steps

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#99]
**Objective**
Write release steps documentation

**Description**
Merge submitting add-on instructions with our steps so that we have a release steps that anyone can follow for OOT 

**Tasks**

- [x] Read https://extensionworkshop.com/documentation/publish/submitting-an-add-on/
- [x] Decide on tags and branch naming convention for releases
- [ ] Document this in README.md
